version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: vacancies-dev
    restart: always
    environment:
      POSTGRES_DB: vacancies
      POSTGRES_USER: shiptenkovlad
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
